/**
 * @typedef {Object} TargetEffectDef
 * @property {string} effect - Unique key used in runtime store (te.effect value)
 * @property {string} label - Display name shown in UI
 * @property {string} description - What the effect actually does
 * @property {string} icon - Font Awesome icon class (e.g. 'fa-volume-xmark')
 * @property {string} cls - CSS class for badge color styling
 * @property {string} group - Category group for the picker UI
 * @property {string[]} [fields] - Extra config fields shown when selected: 'value', 'ability', 'source', 'dc'
 * @property {Object} [defaults] - Default values for config fields
 * @property {string} [sourceLabel] - Override label for the source field
 */

/** @type {TargetEffectDef[]} */
// IMPORTANT: Keep this array sorted alphabetically by label within each group.
// When adding a new effect, insert it in the correct alphabetical position.
const TARGET_EFFECT_DEFINITIONS = [
  // ── Attack ──────────────────────────────────────────────
  {
    effect: 'slasher_enhanced_critical',
    label: 'Attack Disadv',
    description: 'Target has Disadvantage on attack rolls.',
    icon: 'fa-arrow-down',
    cls: 'effect-disadvantage',
    group: 'Attack',
    fields: ['source'],
  },
  {
    effect: 'disadvantage_next_attack',
    label: 'Disadv Next Attack',
    description: 'Disadvantage on the next attack roll.',
    icon: 'fa-arrow-down',
    cls: 'effect-disadvantage',
    group: 'Attack',
    fields: ['source'],
  },
  {
    effect: 'goad',
    label: 'Goad',
    description: 'Attacks against creatures other than the goader have Disadvantage.',
    icon: 'fa-bullseye',
    cls: 'effect-disadvantage',
    group: 'Attack',
    fields: ['source'],
  },
  {
    effect: 'next_attack_bonus',
    label: 'Next Attack +N Bonus',
    description: 'The creature\'s next attack roll gains a bonus.',
    icon: 'fa-bullseye',
    cls: 'effect-target-adv',
    group: 'Attack',
    fields: ['source', 'value'],
    defaults: { value: 5 },
  },
  {
    effect: 'next_attack_advantage',
    label: 'Next Attack Advantage',
    description: 'The creature\'s next attack roll has Advantage.',
    icon: 'fa-arrow-up',
    cls: 'effect-target-adv',
    group: 'Attack',
    fields: ['source'],
  },
  {
    effect: 'distracting_strike_advantage',
    label: 'Next Attack Adv vs Target',
    description: 'The next attack roll against the target has Advantage.',
    icon: 'fa-arrow-up',
    cls: 'effect-target-adv',
    group: 'Attack',
    fields: ['source'],
  },
  {
    effect: 'reckless_attack',
    label: 'Reckless Attack',
    description: 'Attacks have Advantage, but attack rolls against the creature also have Advantage.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Attack',
    fields: ['source'],
  },
  {
    effect: 'taunting_step',
    label: 'Taunted',
    description: 'Disadvantage on attack rolls against creatures other than the taunting source.',
    icon: 'fa-wand-sparkles',
    cls: 'effect-disadvantage',
    group: 'Attack',
    fields: ['source'],
  },

  // ── Defensive ──────────────────────────────────────────
  {
    effect: 'escape_the_horde',
    label: 'Escape the Horde',
    description: 'Attacks against the target have Disadvantage (Escape the Horde).',
    icon: 'fa-shield-halved',
    cls: 'effect-target-disadv',
    group: 'Defensive',
    fields: ['source'],
  },
  {
    effect: 'multiattack_defense',
    label: 'Multiattack Defense',
    description: 'Attacks against the target have Disadvantage (Multiattack Defense).',
    icon: 'fa-shield-halved',
    cls: 'effect-target-disadv',
    group: 'Defensive',
    fields: ['source'],
  },
  {
    effect: 'no_opportunity_attacks',
    label: 'No Opportunity Attacks',
    description: 'The creature cannot make Opportunity Attacks.',
    icon: 'fa-ban',
    cls: 'effect-cannot-act',
    group: 'Defensive',
  },
  {
    effect: 'no_reactions',
    label: 'No Reactions',
    description: 'The creature cannot take Reactions.',
    icon: 'fa-ban',
    cls: 'effect-cannot-act',
    group: 'Defensive',
  },
  {
    effect: 'protection',
    label: 'Protection',
    description: 'Attacks against the target have Disadvantage (Protection fighting style).',
    icon: 'fa-shield-halved',
    cls: 'effect-target-disadv',
    group: 'Defensive',
    fields: ['source'],
  },

  // ── Saves & Checks ──────────────────────────────────────
  {
    effect: 'advantage_abilities',
    label: 'Adv Check',
    description: 'Advantage on all ability checks.',
    icon: 'fa-hand',
    cls: 'effect-buff',
    group: 'Saves & Checks',
    fields: ['source'],
  },
  {
    effect: 'advantage_attacks',
    label: 'Adv',
    description: 'Advantage on attack rolls.',
    icon: 'fa-arrow-up',
    cls: 'effect-buff',
    group: 'Saves & Checks',
    fields: ['source'],
  },
  {
    effect: 'advantage_saves',
    label: 'Adv Save',
    description: 'Advantage on saving throws.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Saves & Checks',
    fields: ['source'],
  },
  {
    effect: 'bane_penalty',
    label: 'Bane (-1d4)',
    description: 'The creature suffers -1d4 on attack rolls and saving throws (Bane).',
    icon: 'fa-shield-halved',
    cls: 'effect-disadvantage',
    group: 'Saves & Checks',
    fields: ['source', 'dc', 'displayLabel'],
    defaults: { dc: 15, displayLabel: 'Bane' },
  },
  {
    effect: 'hex_ability_check_disadvantage',
    label: 'Check Disadv',
    description: 'Disadvantage on ability checks of the chosen ability.',
    icon: 'fa-shield',
    cls: 'effect-disadvantage',
    group: 'Saves & Checks',
    fields: ['ability', 'source'],
    defaults: { ability: 'wis' },
  },
  {
    effect: 'dex_save_disadvantage',
    label: 'DEX Save Disadv',
    description: 'Disadvantage on Dexterity saving throws.',
    icon: 'fa-shield',
    cls: 'effect-disadvantage',
    group: 'Saves & Checks',
  },
  {
    effect: 'disadvantage_perception_checks',
    label: 'Perception Disadv',
    description: 'Disadvantage on Perception checks.',
    icon: 'fa-eye-slash',
    cls: 'effect-disadvantage',
    group: 'Saves & Checks',
  },
  {
    effect: 'hex_save_disadvantage',
    label: 'Save Disadv',
    description: 'Disadvantage on saving throws of the chosen ability.',
    icon: 'fa-shield',
    cls: 'effect-disadvantage',
    group: 'Saves & Checks',
    fields: ['ability', 'source'],
    defaults: { ability: 'wis' },
  },
  {
    effect: 'disadvantage_on_next_save',
    label: 'Save Disadv (Next)',
    description: 'Disadvantage on the creature\'s next saving throw.',
    icon: 'fa-shield',
    cls: 'effect-disadvantage',
    group: 'Saves & Checks',
    fields: ['source'],
  },

  // ── Spells ──────────────────────────────────────────────
  {
    effect: 'holy_aura',
    label: 'Holy Aura',
    description: 'Allies gain Advantage on saving throws. Other creatures have Disadvantage on attack rolls against them. Fiends/Undead that hit an affected creature with a melee attack must succeed on a CON save or be Blinded until the end of their next turn. Concentration, up to 1 minute.',
    icon: 'fa-sun',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'antimagic_field',
    label: 'Antimagic Field',
    description: 'Only weapon attacks are allowed. All magic and spells are suppressed within the field. Expires on concentration loss, initiative roll, short rest, or long rest.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'aura_of_life',
    label: 'Aura of Life',
    description: 'Allies in aura have Resistance to Necrotic damage, HP maximum can\'t be reduced, and regain 1 HP at start of turn if at 0 HP.',
    icon: 'fa-heart-pulse',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'aura_of_purity',
    label: 'Aura of Purity',
    description: 'Resistance to Poison damage, Advantage on saving throws against Blinded, Charmed, Deafened, Frightened, Paralyzed, Poisoned, or Stunned condition.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'aura_of_vitality',
    label: 'Aura of Vitality',
    description: 'Target heals for 2d6 HP when the caster casts the spell. Maintains concentration, allowing free casts once per turn to heal another creature.',
    icon: 'fa-heart-pulse',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'barkskin',
    label: 'Barkskin',
    description: 'Target\'s AC becomes 17. Expires on concentration loss, initiative roll, short rest, or long rest.',
    icon: 'fa-tree',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'blur',
    label: 'Blur',
    description: 'Creatures have Disadvantage on attack rolls against you (unless they have Blindsight or Truesight).',
    icon: 'fa-eye-slash',
    cls: 'effect-target-disadv',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'beacon_of_hope',
    label: 'Beacon of Hope',
    description: 'Advantage on Wisdom saving throws and death saving throws; any healing restores maximum hit points. Expires on concentration loss, initiative roll, short rest, or long rest.',
    icon: 'fa-heart-pulse',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'bless_bonus',
    label: 'Bless (+1d4)',
    description: 'The creature gains +1d4 on attack rolls and saving throws (Bless).',
    icon: 'fa-hands',
    cls: 'effect-bless',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'calm_emotions',
    label: 'Calm Emotions',
    description: 'Suppresses charmed/frightened conditions and grants immunity to Charmed and Frightened, or applies the Charmed condition (concentration).',
    icon: 'fa-hand-holding-heart',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'circle_of_power',
    label: 'Circle of Power',
    description: 'Advantage on saving throws against spells and other magical effects. No damage on a successful save vs half-damage effects.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'clairvoyant_combatant',
    label: 'Clairvoyant Combatant',
    description: 'You have Advantage on attacks vs the target; the target has Disadvantage on attacks vs you.',
    icon: 'fa-eye',
    cls: 'effect-target-adv',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'compelled_duel',
    label: 'Compelled Duel',
    description: 'Disadvantage on attack rolls against creatures other than the source (Concentration, up to 1 minute).',
    icon: 'fa-hand-fist',
    cls: 'effect-disadvantage',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'crown_of_madness',
    label: 'Crown of Madness',
    description: 'The creature is Charmed. On each of its turns, it must use its action to make a melee attack against a creature chosen by the caster before moving.',
    icon: 'fa-crown',
    cls: 'effect-charm',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'death_strike',
    label: 'Death Strike',
    description: 'Double damage on a failed Constitution saving throw (Death Strike).',
    icon: 'fa-skull',
    cls: 'effect-auto-crit',
    group: 'Spells',
    fields: ['source', 'dc'],
    defaults: { dc: 15 },
  },
  {
    effect: 'heroism',
    label: 'Heroism',
    description: 'Target is immune to Frightened and gains temp HP at start of each turn. Concentration, up to 1 minute.',
    icon: 'fa-dragon',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'death_ward',
    label: 'Death Ward',
    description: 'The first time the target would drop to 0 HP, it instead drops to 1 HP. The spell ends.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'enhance_ability',
    label: 'Enhance Ability',
    description: 'The creature has Advantage on ability checks using the chosen ability (Concentration, up to 1 hour).',
    icon: 'fa-hand',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['ability', 'source'],
    defaults: { ability: 'STR' },
  },
  {
    effect: 'flesh_to_stone',
    label: 'Flesh to Stone',
    description: 'The creature is Restrained. On each of its turns, it must make a CON save (DC indicated). On 3 successes, the effect ends. On 3 failures, the creature is Petrified.',
    icon: 'fa-dungeon',
    cls: 'effect-debuff',
    group: 'Spells',
    fields: ['source', 'dc'],
  },
  {
    effect: 'foresight',
    label: 'Foresight',
    description: 'Advantage on d20 tests; attack rolls against the creature have Disadvantage (unless attacker has Blindsight or Truesight).',
    icon: 'fa-eye',
    cls: 'effect-target-adv',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'globe_barrier',
    label: 'Globe of Invulnerability',
    description: 'Creatures inside the globe are protected from spells of 5th level or lower from outside the barrier.',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'ottos_irresistible_dance',
    label: "Otto's Irresistible Dance",
    description: 'The target dances comically. It has the Charmed condition, its speed is 0, it has Disadvantage on Dexterity saving throws and attack rolls, and other creatures have Advantage on attack rolls against it. On each of its turns, the target can repeat the WIS save (DC indicated); on a success, the spell ends.',
    icon: 'fa-music',
    cls: 'effect-debuff',
    group: 'Spells',
    fields: ['source', 'dc'],
  },
  {
    effect: 'regenerate',
    label: 'Regenerate',
    description: 'Target regains 4d8 + 15 HP initially, then 1 HP per turn. When the effect ends, the target is restored to full HP.',
    icon: 'fa-heart-pulse',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'resistance_damage_reduction',
    label: 'Resistance',
    description: 'The creature reduces damage of the chosen type by 1d4 (once per turn).',
    icon: 'fa-shield-halved',
    cls: 'effect-buff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'ray_of_enfeeble_debuff',
    label: 'Ray of Enfeeblement',
    description: 'Disadvantage on Strength-based d20 tests and -1d8 to all damage rolls (Concentration, up to 1 minute).',
    icon: 'fa-hand-fist',
    cls: 'effect-disadvantage',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'resilient_sphere',
    label: 'Resilient Sphere',
    description: 'Target is enclosed in a shimmering sphere. Nothing can pass through the barrier (in or out). The sphere is immune to all damage. Target can use action to roll sphere at half speed. Others can pick up and move it. Disintegrate destroys it. Expires on concentration loss, initiative roll, short rest, or long rest.',
    icon: 'fa-circle',
    cls: 'effect-debuff',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'silenced',
    label: 'Silenced',
    description: 'Deafened and cannot cast spells with Verbal components.',
    icon: 'fa-volume-xmark',
    cls: 'effect-disadvantage',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'summoned',
    label: 'Summoned',
    description: 'This creature was summoned by another creature.',
    icon: 'fa-hand-sparkles',
    cls: 'effect-summoned',
    group: 'Spells',
    fields: ['source'],
  },
  {
    effect: 'pass_without_trace_bonus',
    label: 'Pass Without Trace',
    description: 'The creature gains a +10 bonus to Dexterity (Stealth) checks.',
    icon: 'fa-wind',
    cls: 'effect-target-adv',
    group: 'Spells',
    fields: ['source', 'value'],
    defaults: { value: 10 },
  },

  // ── Movement ────────────────────────────────────────────
  {
    effect: 'ac_penalty',
    label: 'AC Penalty',
    description: 'The creature\'s Armor Class is reduced by N.',
    icon: 'fa-shield-halved',
    cls: 'effect-disadvantage',
    group: 'Movement',
    fields: ['source', 'value'],
    defaults: { value: 2 },
  },
  {
    effect: 'speed_reduction',
    label: 'Speed Reduced',
    description: 'The creature\'s Speed is reduced by N feet.',
    icon: 'fa-minus',
    cls: 'effect-speed-zero',
    group: 'Movement',
    fields: ['source', 'value'],
    defaults: { value: 10 },
  },
]

/**
 * Look up a targetEffect definition by its effect key.
 * Use this in handler code before creating a new targetEffect to ensure it exists in the registry.
 * @param {string} effectKey
 * @returns {TargetEffectDef|undefined}
 */
function getEffectDefinition(effectKey) {
  return TARGET_EFFECT_DEFINITIONS.find(def => def.effect === effectKey)
}

export { TARGET_EFFECT_DEFINITIONS, getEffectDefinition }
