// Centralized feature categorization for both 5e and 2024 rulesets.
// Features are categorized here regardless of source (class, race, background, etc.)

const categories5e = {
    featuresToIgnore: [
        "Ability Score Improvement",
        "Brutal Critical",
        "Channel Divinity",
        "Divine Domain",
        "Domain Spells",
        "Druid Circle",
        "Druidic",
        "Extra Attack",
        "Ki",
        "Martial Archetype",
        "Monastic Tradition",
        "Primal Path",
        "Ranger Archetype",
        "Roguish Archetype",
        "Sacred Oath",
        "Sorcerous Origin",
        "Spellcasting",
    ],

    actions: [
        // "Arcane Charge",
        "Avenging Angel",
        // "Bestial Fury",
        // "Channel Divinity: Abjure Enemy",
        // "Channel Divinity: Charm Animals and Plants",
        // "Channel Divinity: Invoke Duplicity",
        // "Channel Divinity: Knowledge of the Ages",
        // "Channel Divinity: Preserve Life",
        // "Channel Divinity: Radiance of the Dawn",
        // "Channel Divinity: Read Thoughts",
        // "Channel Divinity: Turn the Faithless",
        // "Channel Divinity: Turn Undead",
        // "Cleansing Touch",
        // "Cloak of Shadows",
        // "Countercharm",
        // "Dark Delirium",
        // "Destroy Undead",
        // "Divine Sense",
        // "Divine Strike",
        // "Draconic Presence",
        // "Eldritch Strike",
        // "Empty Body",
        // "Fey Presence",
        // "Holy Nimbus",
        // "Improved Divine Smite",
        // "Improved War Magic",
        // "Master Transmuter",
        // "Primeval Awareness",
        // "Quivering Palm",
        // "Sneak Attack",
        // "Stillness of Mind",
        // "The Third Eye",
        // "Vanish"
    ],

    bonusActions: [
        // "Channel Divinity: Vow of Enmity",
        // "Vow of Enmity",
        // "Combat Wild Shape (Wild Companion)",
        // "Combat Wild Shape",
        // "Cunning Action",
        // "Exceptional Training",
        // "Fast Hands",
        // "Flexible Casting: Converting Spell Slot",
        // "Flexible Casting: Creating Spell Slots",
        // "Font of Magic",
        // "Patient Defense",
        // "Step of the Wind",
        // "Versatile Trickster",
        // "War Magic"
    ],

    reactions: [
        // "Beguiling Defenses",
        "Bend Luck",
        // "Channel Divinity: War God's Blessing",
        // "Entropic Ward",
        // "Instinctive Charm",
        // "Projected Ward",
        // "Wrath of the Storm"
    ],

    characterAdvancement: [
        // "Acolyte of Nature",
        // "Additional Magical Secrets",
        // "Arcane Tradition",
        // "Aura improvements",
        // "Bard College",
        // "Blessings of Knowledge",
        // "Bonus Cantrip",
        // "Bonus Proficiencies",
        // "Bonus Proficiency",
        // "Darkvision",
        // "Divine Health",
        // "Draconic Ancestry",
        // "Draconic Resilience",
        // "Dragon Ancestor",
        // "Dwarven Toughness",
        // "Eldritch Invocations",
        // "Evocation Savant",
        // "Fast Movement",
        // "Favored Enemy",
        // "Fighting Style",
        // "Fleet of Foot",
        // "Hellish Resistance",
        // "High Elf Cantrip",
        // "Mage Hand Legerdemain",
        // "Magical Secrets",
        "Mystic Arcanum",
        // "Martial Arts",
        // "Natural Explorer",
        // "Natural Illusionist",
        // "Oath Spells",
        // "Otherworldly Patron",
        // "Pact Boon",
        // "Pact Magic",
        // "Primal Champion",
        // "Primal Knowledge",
        // "Purity of Body",
        // "Ranger's Companion",
        // "Skillful",
        // "Versatile",
        // "Thieves' Cant",
        // "Timeless Body",
        // "Unarmored Defense",
        // "Unarmored Movement",
        // "Weapon Bond"
    ]
};

const categories2024 = {
    featuresToIgnore: [
        "(capstone - depends on subclass)",
        "Ability Score Improvement",
        "Barbarian Subclass",
        "Bard Subclass",
        "Body and Mind",
        "Channel Divinity",
        "Cleric Subclass",
        "Celestial Resistance",
        "Damage Resistance",
        "Darkvision",
        "Draconic Resilience",
        "Druid Subclass",
        "Druidic",        
        "Eldritch Invocations",
        "Epic Boon",
        "Extra Attack",
        "Evergreen Wild Shape", // Already shown under Archdruid
        "Two Extra Attacks",
        "Three Extra Attacks",
        "Fast Movement",
        "Feat",
        "Feral Senses",
        "Fey Magic",
        "Fighter Subclass",
        "Fighting Style",
        "Foe Slayer",
        "Gnomish Cunning",
        "Heavenly Wings", // Included in Celestial Revelation
        "Implements of Mercy",
        "Improved Combat Superiority",
        "Increased Hit Points",
        "Inner Radiance", // Included in Celestial Revelation
        "Keen Senses",
        "Level 1 Spell",
        "Luck Points",
        "Monk Subclass",
        "Mystic Arcanum (level 7 spell)",
        "Mystic Arcanum (level 8 spell)",
        "Mystic Arcanum (level 9 spell)",
        "Necrotic Shroud", // Included in Celestial Revelation
        "Paladin Subclass",
        "Ranger Subclass",
        "Rogue Subclass",
        "Scholar",
        "Shadow Magic",
        "Skillful",
        "Sorcerer Subclass",
        "Spell Change",
        "Spellcasting",
        "Subclass feature",
        "Thieves' Cant",
        "Trance",
        "Two Cantrips",
        "Unarmored Defense",
        "Unarmored Movement",
        "Ultimate Combat Superiority",
        "Versatile",
        "Warlock Subclass",
        "Wizard Subclass"
    ],

    actions: [
        "Naturally Stealthy"
    ],

    bonusActions: [
        "Nature's Veil"
    ],

    reactions: [
        "Beguiling Defenses",
        "Protection"
    ],

    characterAdvancement: [
        "Additional Fighting Style",
        "Animal Speaker",
        "Avatar of Battle",
        "Bonus Proficiencies",
        "Clockwork Spells",
        "Deft Explorer",
        "Divine Order",
        "Draconic Ancestry",
        "Draconic Spells",
        "Dwarven Resilience",
        "Dwarven Toughness",
        "Expertise",
        "Halfling Nimbleness",
        "Fiendish Legacies",
        "LightBearer",
        "Magical Secrets",
        "Mystic Arcanum",
        "Nature Speaker",
        "Otherworldly Presence",
        "Pact Magic",
        "Primal Order",
        "Psionic Spells",
        "Second-Storywork",
        "Slippery Mind",
        "Student of War"
    ]
};

export function getCategories(ruleset) {
    return ruleset === '2024' ? categories2024 : categories5e;
}

export { categories5e, categories2024 };
