export const SHORT_REST_RESOURCES = [
  'channelDivinityCharges',
  'wildShapeUses',
  'psionicEnergy',
  'focusPoints',
  'superiorityDice',
  'kiPoints',
  'actionsurgeUses',
  'actionSurgeUses',
  'actionSurgeUsedThisRound',
  'adrenalineRushUses',
  '_celestialRevelationUses',
  '_War_Gods_Blessing_active',
   'spellthiefUses',
   'strokeOfLuckUsed',
   'boonOfCombatProwessUsed',
    'encouragingsongUses',
     'piercerPunctureUsedThisTurn',
     'poisonedWeaponsActive',
       '_Savage_Attacker_usedRound',
       '_Shield_Bash_usedRound',
       '_Hamstring_usedRound',
       '_friendsCastTargets'
]

export function getShortRestResources() {
  return [...SHORT_REST_RESOURCES]
}

export const LONG_REST_RESOURCES = [
  'healinghandsUses',
  'ragePoints',
  'bardicInspirationUses',
  'channelDivinityCharges',
  'wildShapeUses',
  'secondWindUses',
  'psionicEnergy',
  'focusPoints',
  'uncannymetabolismUses',
  'sorceryPoints',
  'arcaneRecoveryLevels',
  'superiorityDice',
  'kiPoints',
  'actionSurgeUses',
  'actionSurgeUsedThisRound',
  'layOnHandsPool',
  'preserveLifePool',
  'gloriousDefenseUses',
   'warlockPactMagic',
  'luckyPoints',
  'adrenalineRushUses',
  '_celestialRevelationUses',
  '_War_Gods_Blessing_active',
  'spellthiefUses',
   'strokeOfLuckUsed',
   'boonOfCombatProwessUsed',
   'encouragingsongUses',
    '_Charge_Attack_usedRound',
   '_FastHands_usedRound',
   'clockworkCavalcadeUses',
   '_CunningAction_usedRound',
   '_Cleave_UsedRound',
    '_Nick_UsedRound',
    'surgeUsedRound',
    'illusoryRealityUsedRound',
    'portentUsedThisTurn',
    'psionicStrikeUsedThisTurn',
      '_BrutalStrike_usedRound',
       '_fortifiedHealth_usedRound',
       '_Shield_Bash_usedRound',
        '_Hamstring_usedRound',
        'piercerPunctureUsedThisTurn',
      '_Savage_Attacker_usedRound',
      '_friendsCastTargets',
     'secondWindUses',
   'psionicEnergy',
   'focusPoints',
   'uncannymetabolismUses',
   'sorceryPoints',
   'arcaneRecoveryLevels',
   'superiorityDice',
   'kiPoints',
   'actionSurgeUses',
   'actionSurgeUsedThisRound',
    'layOnHandsPool',
    'preserveLifePool',
    'gloriousDefenseUses',
    'warlockPactMagic',
   'innateSorceryUses',
   'sorcerousRestorationUses',
   'zealousPresenceUses',
   'intimidatingPresenceUses',
   'rageOfTheGodsUses',
   'divineInterventionUses',
   'wholenessofbodyUses',
   'wildResurgenceReversedThisRest',
   'indomitableUses',
   'warriorofthegodsPool',
   'naturalRecoveryFreeCast',
   'naturalRecoveryFreeCastUsed',
   'naturalRecoverySlots',
   'wardingflareUses',
   '_Star_Map_freeCastCount',
   '_Dragon_Companion_freeCastCount',
   '_Contact_Patron_freeCastCount',
   'mysticArcanumLevel6',
   'mysticArcanumLevel7',
   'mysticArcanumLevel8',
   'mysticArcanumLevel9',
   '_Phantasmal_Creatures_freeCastCount',
    '_Fey_Reinforcements_freeCastCount',
     '_Misty_Wanderer_freeCastCount',
     "_Paladin's_Smite_freeCastCount",
        'breathweaponUses',
   'stonecunningUses',
   'naturesVeilUses',
   'favoredEnemyUses',
    'tirelessUses',
    'moonlightStepUses',
    'dreadambushUses',
    'cosmicomenUses',
       'relentlessrageUses',
       'persistentRageUsed',
        'aspectOfTheWildsUsedThisRest',
        'aspectOfTheWildsOption',
     'elderChampionRestUsed',
     'avengingAngelRestUsed',
   'warpingimplosionUses',
   'restorebalanceUses',
   'tranceOfOrderUses',
   'tamedSurgeUses',
     'featsOfChaosUses',
     'featsOfChaosActive',
     'magicalCunningUsed',
      '_Steps_of_the_Fey_freeCastCount',
      '_Detect_Thoughts_freeCastCount',
     'beguilingDefensesUses',
     'healinglightPool',
     'searingvengeanceUses',
     'darkOnesLuckUses',
     '_fiendishResilienceUsed',
     'boonOfCombatProwessUsed',
     'strokeOfLuckUsed',
    '_boonOfEnergyResistanceUsedThisRest',
    '_Energy_Resistances_chosenTypes',
    '_guardedMind_usedRest',
    'poisonedWeaponsActive'
]

export function getLongRestResources() {
  return [...LONG_REST_RESOURCES]
}

export function spellSlotLevels() {
  return [1, 2, 3, 4, 5, 6, 7, 8, 9]
}

const SHORT_REST_RESOURCE_LABELS = [
    { key: 'channelDivinityCharges', label: 'Channel Divinity', classes: ['Cleric', 'Paladin'] },
    { key: 'wildShapeUses', label: 'Wild Shape', classes: ['Druid'] },
    { key: 'secondWindUses', label: 'Second Wind', classes: ['Fighter'] },
    { key: 'actionSurgeUses', label: 'Action Surge', classes: ['Fighter'] },
    { key: 'focusPoints', label: 'Focus Points', classes: ['Monk'] },
    { key: 'psionicEnergy', label: 'Psionic Energy', classes: ['Fighter'], subclasses: ['Psi Warrior'] },
    { key: 'psionicEnergy', label: 'Psionic Energy', classes: ['Rogue'], subclasses: ['Soulknife'] },
    { key: 'superiorityDice', label: 'Superiority Dice', classes: ['Fighter'], subclasses: ['Battle Master'] },
    { key: 'naturalRecoverySlots', label: 'Natural Recovery (Spell Slots)', classes: ['Druid'], subclasses: ['Circle of the Land'] },
    { key: 'arcaneRecoveryLevels', label: 'Arcane Recovery (Spell Slots)', classes: ['Wizard'] }
];

export function getShortRestResourceLabels(playerStats) {
    const className = playerStats?.class?.name;
    const subclassName = playerStats?.class?.subclass?.name || playerStats?.class?.major?.name;

    return SHORT_REST_RESOURCE_LABELS.filter(entry => {
        if (!entry.classes.includes(className)) return false;
        if (entry.subclasses && !entry.subclasses.includes(subclassName)) return false;
        return true;
       }).map(entry => entry.label);
}
